import { RuleValues } from '@/lib/schemas';

export const timeRules: RuleValues[] = [
  {
    id: '1',
    name: 'Tiempo Máximo de Atención',
    description: 'Tiempo límite para atender un cliente',
    value: '5',
    unit: 'minutos',
    type: 'time',
    status: 'Activa',
    priority: 'Alta',
    actions: ['Alerta al supervisor', 'Notificación al operador'],
  },
  {
    id: '2',
    name: 'Tiempo Máximo de Espera',
    description: 'Tiempo límite que un cliente puede esperar en fila',
    value: '15',
    unit: 'minutos',
    type: 'time',
    status: 'Activa',
    priority: 'Muy Alta',
    actions: ['Redistribuir a otra caja', 'Alerta urgente'],
  },
  {
    id: '3',
    name: 'Alerta de Tiempo',
    description: 'Tiempo antes de alcanzar el límite para enviar alerta',
    value: '3',
    unit: 'minutos',
    type: 'time',
    status: 'Activa',
    priority: 'Media',
    actions: ['Notificación preventiva'],
  },
];

export const absenceRules: RuleValues[] = [
  {
    id: '4',
    name: 'Ausencia Máxima',
    description: 'Tiempo máximo que un operador puede estar ausente',
    value: '10',
    unit: 'minutos',
    type: 'absence',
    status: 'Activa',
    priority: 'Alta',
    actions: ['Contactar operador', 'Reasignar clientes'],
  },
  {
    id: '5',
    name: 'Descanso Programado',
    description: 'Duración máxima de descansos programados',
    value: '30',
    unit: 'minutos',
    type: 'absence',
    status: 'Activa',
    priority: 'Media',
    actions: ['Notificación de retorno'],
  },
];

export const priorityRules: RuleValues[] = [
  {
    id: '6',
    name: 'Clientes VIP',
    description: 'Prioridad para clientes con estatus VIP',
    value: '1',
    unit: 'nivel',
    type: 'priority',
    status: 'Activa',
    priority: 'Muy Alta',
    actions: ['Asignación inmediata', 'Caja preferencial'],
    criteria: 'Estatus VIP en sistema',
  },
  {
    id: '7',
    name: 'Adultos Mayores',
    description: 'Prioridad para personas de tercera edad',
    value: '2',
    unit: 'nivel',
    type: 'priority',
    status: 'Activa',
    priority: 'Alta',
    actions: ['Atención preferencial'],
    criteria: 'Edad >= 65 años',
  },
  {
    id: '8',
    name: 'Personas con Discapacidad',
    description: 'Prioridad para personas con discapacidad',
    value: '2',
    unit: 'nivel',
    type: 'priority',
    status: 'Activa',
    priority: 'Alta',
    actions: ['Caja accesible', 'Atención especializada'],
    criteria: 'Certificado de discapacidad',
  },
];
