export const branchData = [
  {
    name: 'Santiago Centro',
    tickets: 245,
    waitTime: '2.5 min',
    serviceTime: '4.2 min',
    satisfaction: 95,
    efficiency: 92,
    status: 'Activo',
  },
  {
    name: 'Providencia',
    tickets: 187,
    waitTime: '3.2 min',
    serviceTime: '4.8 min',
    satisfaction: 92,
    efficiency: 88,
    status: 'Activo',
  },
  {
    name: 'Las Condes',
    tickets: 210,
    waitTime: '3.8 min',
    serviceTime: '5.1 min',
    satisfaction: 90,
    efficiency: 85,
    status: 'Activo',
  },
  {
    name: 'Ñuñoa',
    tickets: 156,
    waitTime: '4.1 min',
    serviceTime: '5.5 min',
    satisfaction: 88,
    efficiency: 82,
    status: 'Activo',
  },
  {
    name: 'Maipú',
    tickets: 178,
    waitTime: '4.5 min',
    serviceTime: '5.8 min',
    satisfaction: 85,
    efficiency: 78,
    status: 'Activo',
  },
  {
    name: 'La Florida',
    tickets: 134,
    waitTime: '5.2 min',
    serviceTime: '6.2 min',
    satisfaction: 82,
    efficiency: 75,
    status: 'Activo',
  },
  {
    name: 'Puente Alto',
    tickets: 145,
    waitTime: '4.8 min',
    serviceTime: '5.9 min',
    satisfaction: 84,
    efficiency: 77,
    status: 'Activo',
  },
];
