export const executives = [
  {
    id: 1,
    name: 'Ana García',
    email: 'ana.garcia@empresa.com',
    phone: '+56 9 2345 6789',
    position: 'Ejecutivo Senior',
    branch: 'Sucursal Centro',
    assignedQueue: 'Caja 1',
    status: 'Activo',
    startDate: '15/03/2022',
    performance: 94,
    satisfaction: 96,
    monthlyClients: 485,
    avgTime: '3:05',
    shift: 'Mañana',
  },
  {
    id: 2,
    name: 'Carlos López',
    email: 'carlos.lopez@empresa.com',
    phone: '+56 9 3456 7890',
    position: 'Ejecutivo',
    branch: 'Sucursal Centro',
    assignedQueue: 'Caja 2',
    status: 'Activo',
    startDate: '22/08/2023',
    performance: 88,
    satisfaction: 91,
    monthlyClients: 420,
    avgTime: '3:45',
    shift: 'Tarde',
  },
  {
    id: 3,
    name: 'María Rodríguez',
    email: 'maria.rodriguez@empresa.com',
    phone: '+56 9 4567 8901',
    position: 'Ejecutivo Senior',
    branch: 'Sucursal Centro',
    assignedQueue: 'Caja 3',
    status: 'Vacaciones',
    startDate: '10/01/2021',
    performance: 92,
    satisfaction: 95,
    monthlyClients: 510,
    avgTime: '2:58',
    shift: 'Mañana',
  },
  {
    id: 4,
    name: 'Juan Pérez',
    email: 'juan.perez@empresa.com',
    phone: '+56 9 5678 9012',
    position: 'Ejecutivo',
    branch: 'Sucursal Centro',
    assignedQueue: 'Virtual 1',
    status: 'Activo',
    startDate: '05/11/2023',
    performance: 90,
    satisfaction: 93,
    monthlyClients: 380,
    avgTime: '3:20',
    shift: 'Mixto',
  },
];
