import { OperatorValues } from '@/lib/schemas';

export const operators: OperatorValues[] = [
  {
    id: 1,
    name: 'Ana García',
    status: 'Atendiendo',
    queue: 'Caja 1',
    currentClient: 'Cliente #045',
    timeWithClient: '2:15',
    avgTime: '3:45',
    served: 12,
    waitingClients: 3,
    lastActivity: 'Hace 30 seg',
    efficiency: 95,
    satisfaction: 94,
  },
  {
    id: 2,
    name: 'Carlos López',
    status: 'Disponible',
    queue: 'Caja 2',
    currentClient: null,
    timeWithClient: null,
    avgTime: '4:12',
    served: 8,
    waitingClients: 5,
    lastActivity: 'Hace 1 min',
    efficiency: 88,
    satisfaction: 91,
  },
  {
    id: 3,
    name: 'María Rodríguez',
    status: 'Ausente',
    queue: 'Caja 3',
    currentClient: null,
    timeWithClient: null,
    avgTime: '3:28',
    served: 15,
    waitingClients: 8,
    lastActivity: 'Hace 12 min',
    efficiency: 92,
    satisfaction: 96,
  },
  {
    id: 4,
    name: 'Juan Pérez',
    status: 'Atendiendo',
    queue: 'Virtual 1',
    currentClient: 'Cliente #052',
    timeWithClient: '4:32',
    avgTime: '2:56',
    served: 20,
    waitingClients: 2,
    lastActivity: 'Hace 10 seg',
    efficiency: 98,
    satisfaction: 93,
  },
  {
    id: 5,
    name: 'Laura Martín',
    status: 'Descanso',
    queue: 'Mixta 1',
    currentClient: null,
    timeWithClient: null,
    avgTime: '3:15',
    served: 11,
    waitingClients: 4,
    lastActivity: 'Hace 8 min',
    efficiency: 90,
    satisfaction: 89,
  },
];
